### ISSUE TITLE
Fixes for plugins repository publication

### ISSUE THREAD

**Issue by huston007** [olegbakhirev/crowdin-status-widget#1]
1. "Please enter correct token and project ID" message is shown until initial loading done
<img width="590" alt="screen shot 2018-07-20 at 12 22 41" src="https://user-images.githubusercontent.com/4318513/42994946-360d8e90-8c18-11e8-85c1-aa72152b06c1.png">

2. Wrong font is used for project title, should be taken from ring
<img width="162" alt="screen shot 2018-07-20 at 12 24 10" src="https://user-images.githubusercontent.com/4318513/42994955-3b24328a-8c18-11e8-9e02-2600eccb340f.png">

3. Links should be done in Ring UI colors (Link component of Ring UI should be used)
<img width="189" alt="screen shot 2018-07-20 at 12 24 14" src="https://user-images.githubusercontent.com/4318513/42995122-b79035e4-8c18-11e8-8ded-85250200aca2.png">

**Comment by olegbakhirev** [comment]
Fixed
