### ISSUE TITLE
v1 API no longer functional

### ISSUE THREAD

**Issue by charliefoxtwo** [olegbakhirev/crowdin-status-widget#20]
Per the [v1 docs](https://developer.crowdin.com/assets/api/api_v1_docs_crowdin.pdf), it seems the v1 API ceased functioning at the end of 2021 and has been superseded by the [v2 API](https://developer.crowdin.com/api/v2).

![image](https://github.com/olegbakhirev/crowdin-status-widget/assets/30303272/ec7b0712-3d58-4c51-b768-5aa7ddf07720)

As such, it seems this widget no longer works as it utilizes the v1 API (at least, that's the way it appears to me).

**Comment by inson1** [comment]
@olegbakhirev Hi :) Do you plan to fix it?

**Comment by olegbakhirev** [comment]
@inson1 Sorry for delay with the response. Yep I will plan this activity but as far as I can see it is still functional with old API. 
So in my case widget still works with old API

**Comment by olegbakhirev** [comment]
Pushed new version and code changes
